import 'package:flutter/material.dart';

enum AppTheme {
  warmClay, iris, clearSky, morningSlate,
  softDusk, deepFocus, forestFloor, goldenHour, nightBloom, sandDune,
}

extension AppThemeX on AppTheme {
  bool get isDark => this == AppTheme.deepFocus || this == AppTheme.nightBloom;
}

class AppColorScheme {
  final Color bgGradientTop;
  final Color bgGradientMid;
  final Color bgGradientBottom;
  final double bgGradientTopOpacity;
  final double bgGradientMidOpacity;
  final double bgGradientBottomOpacity;
  final Color cardBackground;
  final double cardBackgroundOpacity;
  final Color cardPinned;
  final double cardPinnedOpacity;
  final Color cardDone;
  final double cardDoneOpacity;
  final Color cardBrowse;
  final double cardBrowseOpacity;
  final Color ctaPrimary;
  final Color ctaSecondary;
  final Color accentPinned;
  final Color accentRegular;
  final Color accentCustom;
  final Color accentMuted;
  final Color textPrimary;
  final Color textSecondary;
  final Color textLabel;
  final Color textSubtitle;
  final Color textTertiary;
  final Color textDisabled;
  final Color textMutedBrown;
  final Color borderCard;
  final double borderCardOpacity;
  final Color borderMedium;
  final Color borderWarm;
  final Color divider;
  final double dividerOpacity;
  final Color checkmarkFill;
  final Color checkmarkBackground;
  final double checkmarkBackgroundOpacity;
  final Color profileCard;
  final double profileCardOpacity;
  final Color momentsCard;
  final double momentsCardOpacity;
  final Color modalBg1;
  final Color modalBg2;
  final Color modalBg3;
  final Color modalShadow;
  final Color modalInnerShadow;
  final Color buttonDark;
  final Color buttonText;
  final Color surfaceLight;
  final Color surfaceLightest;
  final Color tabBarFade;
  final Color barrierColor;
  final double barrierOpacity;
  final Color destructive;
  final Color destructiveDark;
  final Color error;
  final Color success;
  final Color toastText;
  final Color onboardingBg1;
  final Color onboardingBg2;
  final Color onboardingBg3;
  final Color onboardingBg4;
  final Color catHealth;
  final Color catMood;
  final Color catProductivity;
  final Color catHome;
  final Color catRelationships;
  final Color catCreativity;
  final Color catFinances;
  final Color catSelfCare;
  final String backgroundSoft;  // habits + progress screens
  final String backgroundMs;    // moments screen
  final Color ctaAlternative;
  final Color completionHeart;
  final Color heartHighlight;
  final Color heartDeep;
  final Color pinnedAccent;

  const AppColorScheme({
    required this.bgGradientTop,
    required this.bgGradientMid,
    required this.bgGradientBottom,
    required this.bgGradientTopOpacity,
    required this.bgGradientMidOpacity,
    required this.bgGradientBottomOpacity,
    required this.cardBackground,
    required this.cardBackgroundOpacity,
    required this.cardPinned,
    required this.cardPinnedOpacity,
    required this.cardDone,
    required this.cardDoneOpacity,
    required this.cardBrowse,
    required this.cardBrowseOpacity,
    required this.ctaPrimary,
    required this.ctaSecondary,
    required this.accentPinned,
    required this.accentRegular,
    required this.accentCustom,
    required this.accentMuted,
    required this.textPrimary,
    required this.textSecondary,
    required this.textLabel,
    required this.textSubtitle,
    required this.textTertiary,
    required this.textDisabled,
    required this.textMutedBrown,
    required this.borderCard,
    required this.borderCardOpacity,
    required this.borderMedium,
    required this.borderWarm,
    required this.divider,
    required this.dividerOpacity,
    required this.checkmarkFill,
    required this.checkmarkBackground,
    required this.checkmarkBackgroundOpacity,
    required this.profileCard,
    required this.profileCardOpacity,
    required this.momentsCard,
    required this.momentsCardOpacity,
    required this.modalBg1,
    required this.modalBg2,
    required this.modalBg3,
    required this.modalShadow,
    required this.modalInnerShadow,
    required this.buttonDark,
    required this.buttonText,
    required this.surfaceLight,
    required this.surfaceLightest,
    required this.tabBarFade,
    required this.barrierColor,
    required this.barrierOpacity,
    required this.destructive,
    required this.destructiveDark,
    required this.error,
    required this.success,
    required this.toastText,
    required this.onboardingBg1,
    required this.onboardingBg2,
    required this.onboardingBg3,
    required this.onboardingBg4,
    required this.catHealth,
    required this.catMood,
    required this.catProductivity,
    required this.catHome,
    required this.catRelationships,
    required this.catCreativity,
    required this.catFinances,
    required this.catSelfCare,
    required this.backgroundSoft,
    required this.backgroundMs,
    required this.ctaAlternative,
    required this.completionHeart,
    required this.heartHighlight,
    required this.heartDeep,
    required this.pinnedAccent,
  });
}

class AppColors {
  static const Color catHealth =        Color(0xFFD96766);
  static const Color catMood =          Color(0xFF9B8299);
  static const Color catProductivity =  Color(0xFF8B9A6B);
  static const Color catHome =          Color(0xFF7B9E8A);
  static const Color catRelationships = Color(0xFFC4856E);
  static const Color catCreativity =    Color(0xFFB48BA3);
  static const Color catFinances =      Color(0xFFC49B5A);
  static const Color catSelfCare =      Color(0xFFB8A089);

  /// Maps focus area name → category accent color.
  static const Map<String, Color> categoryColors = {
    'Health': catHealth,
    'Mood': catMood,
    'Productivity': catProductivity,
    'Home & organization': catHome,
    'Relationships': catRelationships,
    'Creativity': catCreativity,
    'Finances': catFinances,
    'Self-care': catSelfCare,
  };

  static const AppColorScheme warmClay = AppColorScheme(
    bgGradientTop:               Color(0xFFF2D4B0),
    bgGradientMid:               Color(0xFFE8BFA0),
    bgGradientBottom:            Color(0xFFD49A70),
    bgGradientTopOpacity:        0.15,
    bgGradientMidOpacity:        0.38,
    bgGradientBottomOpacity:     0.55,
    cardBackground:              Color(0xFFF9EBE0),
    cardBackgroundOpacity:       0.28,
    cardPinned:                  Color(0xFFFCF5EF),
    cardPinnedOpacity:           0.38,
    cardDone:                    Color(0xFFFFFFFF),
    cardDoneOpacity:             0.22,
    cardBrowse:                  Color(0xFFFFFFFF),
    cardBrowseOpacity:           0.40,
    ctaPrimary:                  Color(0xFF8B7563),
    ctaSecondary:                Color(0xFF7A6B5F),
    accentPinned:                Color(0xFFD96766),
    accentRegular:               Color(0xFFC19E8B),
    accentCustom:                Color(0xFFC49989),
    accentMuted:                 Color(0xFFA89181),
    textPrimary:                 Color(0xFF3C342A),
    textSecondary:               Color(0xFF9A8A78),
    textLabel:                   Color(0xFF8B7563),
    textSubtitle:                Color(0xFF6B5D52),
    textTertiary:                Color(0xFF9B8A7A),
    textDisabled:                Color(0xFFCFC0B0),
    textMutedBrown:              Color(0xFF9A8566),
    borderCard:                  Color(0xFFFFFFFF),
    borderCardOpacity:           0.18,
    borderMedium:                Color(0xFFD8D2C8),
    borderWarm:                  Color(0xFFE8E3DB),
    divider:                     Color(0xFF8B7563),
    dividerOpacity:              0.15,
    checkmarkFill:               Color(0xFF7A6A58),
    checkmarkBackground:         Color(0xFFD9CFC6),
    checkmarkBackgroundOpacity:  0.40,
    profileCard:                 Color(0xFFFFFFFF),
    profileCardOpacity:          0.50,
    momentsCard:                 Color(0xFFFFFFFF),
    momentsCardOpacity:          0.25,
    modalBg1:                    Color(0xFFF5ECE0),
    modalBg2:                    Color(0xFFEDE4D8),
    modalBg3:                    Color(0xFFE6DDD1),
    modalShadow:                 Color(0xFF32281E),
    modalInnerShadow:            Color(0xFFB4A591),
    buttonDark:                  Color(0xFF6B5B4A),
    buttonText:                  Color(0xFFF6F5F1),
    surfaceLight:                Color(0xFFF8F5F2),
    surfaceLightest:             Color(0xFFFAF7F2),
    tabBarFade:                  Color(0xFFA88A70),
    barrierColor:                Color(0xFF504638),
    barrierOpacity:              0.28,
    destructive:                 Color(0xFFC44B3F),
    destructiveDark:             Color(0xFFB5524D),
    error:                       Color(0xFFD84315),
    success:                     Color(0xFF6A8B6F),
    toastText:                   Color(0xFF4A3F35),
    onboardingBg1:               Color(0xFFF5EDE0),
    onboardingBg2:               Color(0xFFE8DCC8),
    onboardingBg3:               Color(0xFFDDD1C0),
    onboardingBg4:               Color(0xFFD9CDB8),
    catHealth:        Color(0xFFD96766),
    catMood:          Color(0xFF9B8299),
    catProductivity:  Color(0xFF8B9A6B),
    catHome:          Color(0xFF7B9E8A),
    catRelationships: Color(0xFFC4856E),
    catCreativity:    Color(0xFFB48BA3),
    catFinances:      Color(0xFFC49B5A),
    catSelfCare:      Color(0xFFB8A089),
    backgroundSoft:  'assets/images/background_soft_warm_clay.png',
    backgroundMs:    'assets/images/background_ms_warm_clay.png',
    ctaAlternative:  Color(0xFF6B8E6E),
    completionHeart: Color(0xFFC4908A),
    heartHighlight:  Color(0xFFE5B5B0),
    heartDeep:       Color(0xFFC99090),
    pinnedAccent:    Color(0xFFD46A2A),
  );

  static const AppColorScheme iris = AppColorScheme(
    bgGradientTop:               Color(0xFFD4CCE8),
    bgGradientMid:               Color(0xFFC8BEE0),
    bgGradientBottom:            Color(0xFFAA9AD4),
    bgGradientTopOpacity:        0.15,
    bgGradientMidOpacity:        0.38,
    bgGradientBottomOpacity:     0.55,
    cardBackground:              Color(0xFFEDE8F8),
    cardBackgroundOpacity:       0.28,
    cardPinned:                  Color(0xFFF5F1FB),
    cardPinnedOpacity:           0.38,
    cardDone:                    Color(0xFFFFFFFF),
    cardDoneOpacity:             0.22,
    cardBrowse:                  Color(0xFFFFFFFF),
    cardBrowseOpacity:           0.40,
    ctaPrimary:                  Color(0xFF5547A0),
    ctaSecondary:                Color(0xFF4A3D8F),
    accentPinned:                Color(0xFFD96766),
    accentRegular:               Color(0xFF8878C8),
    accentCustom:                Color(0xFF9888C8),
    accentMuted:                 Color(0xFF8878B0),
    textPrimary:                 Color(0xFF26204A),
    textSecondary:               Color(0xFF6E66A0),
    textLabel:                   Color(0xFF5547A0),
    textSubtitle:                Color(0xFF4A4270),
    textTertiary:                Color(0xFF7E74A8),
    textDisabled:                Color(0xFFBEB8D8),
    textMutedBrown:              Color(0xFF7A6E9A),
    borderCard:                  Color(0xFFFFFFFF),
    borderCardOpacity:           0.18,
    borderMedium:                Color(0xFFCCC6DC),
    borderWarm:                  Color(0xFFDDD8EC),
    divider:                     Color(0xFF5547A0),
    dividerOpacity:              0.15,
    checkmarkFill:               Color(0xFF5547A0),
    checkmarkBackground:         Color(0xFFCFC8E8),
    checkmarkBackgroundOpacity:  0.40,
    profileCard:                 Color(0xFFFFFFFF),
    profileCardOpacity:          0.50,
    momentsCard:                 Color(0xFFFFFFFF),
    momentsCardOpacity:          0.25,
    modalBg1:                    Color(0xFFECE6F8),
    modalBg2:                    Color(0xFFF0EBF8),
    modalBg3:                    Color(0xFFF4F0FA),
    modalShadow:                 Color(0xFF1E1840),
    modalInnerShadow:            Color(0xFF9A8EC8),
    buttonDark:                  Color(0xFF3E3478),
    buttonText:                  Color(0xFFF5F2FA),
    surfaceLight:                Color(0xFFF2EFF8),
    surfaceLightest:             Color(0xFFF8F6FC),
    tabBarFade:                  Color(0xFF9A90B8),
    barrierColor:                Color(0xFF2E2650),
    barrierOpacity:              0.28,
    destructive:                 Color(0xFFC44B3F),
    destructiveDark:             Color(0xFFB5524D),
    error:                       Color(0xFFD84315),
    success:                     Color(0xFF6A8B6F),
    toastText:                   Color(0xFF332B58),
    onboardingBg1:               Color(0xFFEDE5F5),
    onboardingBg2:               Color(0xFFDDD4EC),
    onboardingBg3:               Color(0xFFD0C6E2),
    onboardingBg4:               Color(0xFFC8BCD8),
    catHealth:        Color(0xFFD96766),
    catMood:          Color(0xFF9B8299),
    catProductivity:  Color(0xFF8B9A6B),
    catHome:          Color(0xFF7B9E8A),
    catRelationships: Color(0xFFC4856E),
    catCreativity:    Color(0xFFB48BA3),
    catFinances:      Color(0xFFC49B5A),
    catSelfCare:      Color(0xFFB8A089),
    backgroundSoft:  'assets/images/background_soft_iris.png',
    backgroundMs:    'assets/images/background_ms_iris.png',
    ctaAlternative:  Color(0xFF7C6FC4),
    completionHeart: Color(0xFF9888C8),
    heartHighlight:  Color(0xFFBFB0E8),
    heartDeep:       Color(0xFF9070C8),
    pinnedAccent:    Color(0xFF7B5EA7),
  );

  static const AppColorScheme clearSky = AppColorScheme(
    bgGradientTop:               Color(0xFFBDD4E8),
    bgGradientMid:               Color(0xFFADC8E0),
    bgGradientBottom:            Color(0xFF88B2D8),
    bgGradientTopOpacity:        0.15,
    bgGradientMidOpacity:        0.38,
    bgGradientBottomOpacity:     0.55,
    cardBackground:              Color(0xFFE5EEF8),
    cardBackgroundOpacity:       0.28,
    cardPinned:                  Color(0xFFF0F5FC),
    cardPinnedOpacity:           0.38,
    cardDone:                    Color(0xFFFFFFFF),
    cardDoneOpacity:             0.22,
    cardBrowse:                  Color(0xFFFFFFFF),
    cardBrowseOpacity:           0.40,
    ctaPrimary:                  Color(0xFF4A7BAD),
    ctaSecondary:                Color(0xFF3D6A9A),
    accentPinned:                Color(0xFFD96766),
    accentRegular:               Color(0xFF82B0D4),
    accentCustom:                Color(0xFF92B8D8),
    accentMuted:                 Color(0xFF88A4BE),
    textPrimary:                 Color(0xFF1E3145),
    textSecondary:               Color(0xFF637D96),
    textLabel:                   Color(0xFF4A7BAD),
    textSubtitle:                Color(0xFF3D5568),
    textTertiary:                Color(0xFF7B95AC),
    textDisabled:                Color(0xFFB8CAD8),
    textMutedBrown:              Color(0xFF6E8698),
    borderCard:                  Color(0xFFFFFFFF),
    borderCardOpacity:           0.18,
    borderMedium:                Color(0xFFC4D2DE),
    borderWarm:                  Color(0xFFD8E4EE),
    divider:                     Color(0xFF4A7BAD),
    dividerOpacity:              0.15,
    checkmarkFill:               Color(0xFF4A7BAD),
    checkmarkBackground:         Color(0xFFC4D5E6),
    checkmarkBackgroundOpacity:  0.40,
    profileCard:                 Color(0xFFFFFFFF),
    profileCardOpacity:          0.50,
    momentsCard:                 Color(0xFFFFFFFF),
    momentsCardOpacity:          0.25,
    modalBg1:                    Color(0xFFE6EFF8),
    modalBg2:                    Color(0xFFECF2F8),
    modalBg3:                    Color(0xFFF2F6FA),
    modalShadow:                 Color(0xFF162838),
    modalInnerShadow:            Color(0xFF8AACC8),
    buttonDark:                  Color(0xFF345878),
    buttonText:                  Color(0xFFF2F6FA),
    surfaceLight:                Color(0xFFF0F4F8),
    surfaceLightest:             Color(0xFFF6F9FC),
    tabBarFade:                  Color(0xFF80A4BE),
    barrierColor:                Color(0xFF243848),
    barrierOpacity:              0.28,
    destructive:                 Color(0xFFC44B3F),
    destructiveDark:             Color(0xFFB5524D),
    error:                       Color(0xFFD84315),
    success:                     Color(0xFF6A8B6F),
    toastText:                   Color(0xFF2A4458),
    onboardingBg1:               Color(0xFFE5EFF8),
    onboardingBg2:               Color(0xFFD4E2F0),
    onboardingBg3:               Color(0xFFC5D6E6),
    onboardingBg4:               Color(0xFFBAD0E0),
    catHealth:        Color(0xFFD96766),
    catMood:          Color(0xFF9B8299),
    catProductivity:  Color(0xFF8B9A6B),
    catHome:          Color(0xFF7B9E8A),
    catRelationships: Color(0xFFC4856E),
    catCreativity:    Color(0xFFB48BA3),
    catFinances:      Color(0xFFC49B5A),
    catSelfCare:      Color(0xFFB8A089),
    backgroundSoft:  'assets/images/background_soft_clear_sky.png',
    backgroundMs:    'assets/images/background_ms_clear_sky.png',
    ctaAlternative:  Color(0xFF4A7BAD),
    completionHeart: Color(0xFF82B0D4),
    heartHighlight:  Color(0xFFAAD0E8),
    heartDeep:       Color(0xFF6AA0C8),
    pinnedAccent:    Color(0xFF2E86AB),
  );

  static const AppColorScheme morningSlate = AppColorScheme(
    bgGradientTop:               Color(0xFFB8C8C4),
    bgGradientMid:               Color(0xFFA8BCB8),
    bgGradientBottom:            Color(0xFF82A8A4),
    bgGradientTopOpacity:        0.15,
    bgGradientMidOpacity:        0.38,
    bgGradientBottomOpacity:     0.55,
    cardBackground:              Color(0xFFE0EAE8),
    cardBackgroundOpacity:       0.28,
    cardPinned:                  Color(0xFFEEF4F3),
    cardPinnedOpacity:           0.38,
    cardDone:                    Color(0xFFFFFFFF),
    cardDoneOpacity:             0.22,
    cardBrowse:                  Color(0xFFFFFFFF),
    cardBrowseOpacity:           0.40,
    ctaPrimary:                  Color(0xFF4E7A75),
    ctaSecondary:                Color(0xFF3D6560),
    accentPinned:                Color(0xFFD96766),
    accentRegular:               Color(0xFF8DB5B0),
    accentCustom:                Color(0xFF9DBFBA),
    accentMuted:                 Color(0xFF88A8A4),
    textPrimary:                 Color(0xFF253332),
    textSecondary:               Color(0xFF6B8580),
    textLabel:                   Color(0xFF4E7A75),
    textSubtitle:                Color(0xFF3E5855),
    textTertiary:                Color(0xFF7B9894),
    textDisabled:                Color(0xFFB8CAC8),
    textMutedBrown:              Color(0xFF6E8884),
    borderCard:                  Color(0xFFFFFFFF),
    borderCardOpacity:           0.18,
    borderMedium:                Color(0xFFC4D2D0),
    borderWarm:                  Color(0xFFD8E6E4),
    divider:                     Color(0xFF4E7A75),
    dividerOpacity:              0.15,
    checkmarkFill:               Color(0xFF4E7A75),
    checkmarkBackground:         Color(0xFFC8D6D4),
    checkmarkBackgroundOpacity:  0.40,
    profileCard:                 Color(0xFFFFFFFF),
    profileCardOpacity:          0.50,
    momentsCard:                 Color(0xFFFFFFFF),
    momentsCardOpacity:          0.25,
    modalBg1:                    Color(0xFFE4EEEC),
    modalBg2:                    Color(0xFFEAF2F0),
    modalBg3:                    Color(0xFFF0F6F5),
    modalShadow:                 Color(0xFF1A2E2C),
    modalInnerShadow:            Color(0xFF8AB0AC),
    buttonDark:                  Color(0xFF365854),
    buttonText:                  Color(0xFFF2F6F5),
    surfaceLight:                Color(0xFFEEF4F2),
    surfaceLightest:             Color(0xFFF5F9F8),
    tabBarFade:                  Color(0xFF7A9694),
    barrierColor:                Color(0xFF283E3C),
    barrierOpacity:              0.28,
    destructive:                 Color(0xFFC44B3F),
    destructiveDark:             Color(0xFFB5524D),
    error:                       Color(0xFFD84315),
    success:                     Color(0xFF6A8B6F),
    toastText:                   Color(0xFF2C4442),
    onboardingBg1:               Color(0xFFE2EEE8),
    onboardingBg2:               Color(0xFFD0E0DA),
    onboardingBg3:               Color(0xFFC2D4CE),
    onboardingBg4:               Color(0xFFB8CCC6),
    catHealth:        Color(0xFFD96766),
    catMood:          Color(0xFF9B8299),
    catProductivity:  Color(0xFF8B9A6B),
    catHome:          Color(0xFF7B9E8A),
    catRelationships: Color(0xFFC4856E),
    catCreativity:    Color(0xFFB48BA3),
    catFinances:      Color(0xFFC49B5A),
    catSelfCare:      Color(0xFFB8A089),
    backgroundSoft:  'assets/images/background_soft_morning_slate.png',
    backgroundMs:    'assets/images/background_ms_morning_slate.png',
    ctaAlternative:  Color(0xFF4E7A75),
    completionHeart: Color(0xFF8DB5B0),
    heartHighlight:  Color(0xFFAAC8C4),
    heartDeep:       Color(0xFF6A9E99),
    pinnedAccent:    Color(0xFF4A7C59),
  );

  // ── Soft Dusk ─────────────────────────────────────────────────────
  static const AppColorScheme softDusk = AppColorScheme(
    bgGradientTop:               Color(0xFFEBB4AF),
    bgGradientMid:               Color(0xFFE3AAA6),
    bgGradientBottom:            Color(0xFFDC9090),
    bgGradientTopOpacity:        0.82,
    bgGradientMidOpacity:        0.86,
    bgGradientBottomOpacity:     0.90,
    cardBackground:              Color(0xFFFFDCE1),
    cardBackgroundOpacity:       0.28,
    cardPinned:                  Color(0xFFFFF0F2),
    cardPinnedOpacity:           0.38,
    cardDone:                    Color(0xFFFFFFFF),
    cardDoneOpacity:             0.22,
    cardBrowse:                  Color(0xFFFFFFFF),
    cardBrowseOpacity:           0.40,
    ctaPrimary:                  Color(0xFFD4707A),
    ctaSecondary:                Color(0xFFC06068),
    accentPinned:                Color(0xFFD4707A),
    accentRegular:               Color(0xFFE0A0A8),
    accentCustom:                Color(0xFFD88890),
    accentMuted:                 Color(0xFFB88090),
    textPrimary:                 Color(0xFF3D2528),
    textSecondary:               Color(0xFF9B6070),
    textLabel:                   Color(0xFF9B6070),
    textSubtitle:                Color(0xFF6D4450),
    textTertiary:                Color(0xFFB07080),
    textDisabled:                Color(0xFFD4B0B8),
    textMutedBrown:              Color(0xFF9B6070),
    borderCard:                  Color(0xFFFFC8D2),
    borderCardOpacity:           0.55,
    borderMedium:                Color(0xFFDEB8C0),
    borderWarm:                  Color(0xFFECC8D0),
    divider:                     Color(0xFFD4707A),
    dividerOpacity:              0.20,
    checkmarkFill:               Color(0xFFD4707A),
    checkmarkBackground:         Color(0xFFE8B0B8),
    checkmarkBackgroundOpacity:  0.40,
    profileCard:                 Color(0xFFFFFFFF),
    profileCardOpacity:          0.50,
    momentsCard:                 Color(0xFFFFFFFF),
    momentsCardOpacity:          0.25,
    modalBg1:                    Color(0xFFF5E0E2),
    modalBg2:                    Color(0xFFF0D8DA),
    modalBg3:                    Color(0xFFECD0D2),
    modalShadow:                 Color(0xFF3D2528),
    modalInnerShadow:            Color(0xFFB88890),
    buttonDark:                  Color(0xFFB05060),
    buttonText:                  Color(0xFFFFF0F0),
    surfaceLight:                Color(0xFFF8EEEE),
    surfaceLightest:             Color(0xFFFCF4F4),
    tabBarFade:                  Color(0xFFC08886),
    barrierColor:                Color(0xFF503038),
    barrierOpacity:              0.28,
    destructive:                 Color(0xFFC44B3F),
    destructiveDark:             Color(0xFFB5524D),
    error:                       Color(0xFFD84315),
    success:                     Color(0xFF6A8B6F),
    toastText:                   Color(0xFF3D2528),
    onboardingBg1:               Color(0xFFF0D4CE),
    onboardingBg2:               Color(0xFFE8C4BE),
    onboardingBg3:               Color(0xFFE0B4AE),
    onboardingBg4:               Color(0xFFD8A8A2),
    catHealth:        Color(0xFFD96766),
    catMood:          Color(0xFF9B8299),
    catProductivity:  Color(0xFF8B9A6B),
    catHome:          Color(0xFF7B9E8A),
    catRelationships: Color(0xFFC4856E),
    catCreativity:    Color(0xFFB48BA3),
    catFinances:      Color(0xFFC49B5A),
    catSelfCare:      Color(0xFFB8A089),
    backgroundSoft:  'assets/images/background_soft_softdusk.png',
    backgroundMs:    'assets/images/background_ms_softdusk.png',
    ctaAlternative:  Color(0xFFC46878),
    completionHeart: Color(0xFFD88890),
    heartHighlight:  Color(0xFFE8A8B0),
    heartDeep:       Color(0xFFC06070),
    pinnedAccent:    Color(0xFFD4707A),
  );

  // ── Deep Focus ────────────────────────────────────────────────────
  static const AppColorScheme deepFocus = AppColorScheme(
    bgGradientTop:               Color(0xFF1E1E22),
    bgGradientMid:               Color(0xFF242428),
    bgGradientBottom:            Color(0xFF2A2A2E),
    bgGradientTopOpacity:        0.45,
    bgGradientMidOpacity:        0.55,
    bgGradientBottomOpacity:     0.65,
    cardBackground:              Color(0xFF36363A),
    cardBackgroundOpacity:       0.83,
    cardPinned:                  Color(0xFF3E3E42),
    cardPinnedOpacity:           0.83,
    cardDone:                    Color(0xFF2A2A2E),
    cardDoneOpacity:             0.70,
    cardBrowse:                  Color(0xFF303034),
    cardBrowseOpacity:           0.80,
    ctaPrimary:                  Color(0xFFC9A96E),
    ctaSecondary:                Color(0xFFB89858),
    accentPinned:                Color(0xFFC9A96E),
    accentRegular:               Color(0xFF6E6458),
    accentCustom:                Color(0xFF8A7A60),
    accentMuted:                 Color(0xFF5A5248),
    textPrimary:                 Color(0xFFE8E4DF),
    textSecondary:               Color(0xFFB8B0A8),
    textLabel:                   Color(0xFF9B9590),
    textSubtitle:                Color(0xFFD0C8C0),
    textTertiary:                Color(0xFF9B9590),
    textDisabled:                Color(0xFF6A6460),
    textMutedBrown:              Color(0xFF9B9590),
    borderCard:                  Color(0xFF524E44),
    borderCardOpacity:           0.52,
    borderMedium:                Color(0xFF4A4640),
    borderWarm:                  Color(0xFF5A5448),
    divider:                     Color(0xFFC9A96E),
    dividerOpacity:              0.18,
    checkmarkFill:               Color(0xFFC9A96E),
    checkmarkBackground:         Color(0xFF5A5248),
    checkmarkBackgroundOpacity:  0.60,
    profileCard:                 Color(0xFF36363A),
    profileCardOpacity:          0.90,
    momentsCard:                 Color(0xFF2E2E32),
    momentsCardOpacity:          0.80,
    modalBg1:                    Color(0xFF28282C),
    modalBg2:                    Color(0xFF2E2E32),
    modalBg3:                    Color(0xFF343438),
    modalShadow:                 Color(0xFF000000),
    modalInnerShadow:            Color(0xFF4A4640),
    buttonDark:                  Color(0xFFC9A96E),
    buttonText:                  Color(0xFF1E1E22),
    surfaceLight:                Color(0xFF2E2E32),
    surfaceLightest:             Color(0xFF343438),
    tabBarFade:                  Color(0xFF141418),
    barrierColor:                Color(0xFF000000),
    barrierOpacity:              0.45,
    destructive:                 Color(0xFFE06050),
    destructiveDark:             Color(0xFFD05545),
    error:                       Color(0xFFE85535),
    success:                     Color(0xFF7A9B7A),
    toastText:                   Color(0xFFE8E4DF),
    onboardingBg1:               Color(0xFF1E1E22),
    onboardingBg2:               Color(0xFF242428),
    onboardingBg3:               Color(0xFF2A2A2E),
    onboardingBg4:               Color(0xFF303034),
    catHealth:        Color(0xFFE07A78),
    catMood:          Color(0xFFB098B0),
    catProductivity:  Color(0xFFA0B080),
    catHome:          Color(0xFF90B4A0),
    catRelationships: Color(0xFFD8A088),
    catCreativity:    Color(0xFFC8A0B8),
    catFinances:      Color(0xFFD8B070),
    catSelfCare:      Color(0xFFC8B098),
    backgroundSoft:  'assets/images/background_soft_deepfocus.png',
    backgroundMs:    'assets/images/background_ms_deepfocus.png',
    ctaAlternative:  Color(0xFFC9A96E),
    completionHeart: Color(0xFFC9A96E),
    heartHighlight:  Color(0xFFD8BF88),
    heartDeep:       Color(0xFFB89858),
    pinnedAccent:    Color(0xFFC9A96E),
  );

  // ── Forest Floor ──────────────────────────────────────────────────
  static const AppColorScheme forestFloor = AppColorScheme(
    bgGradientTop:               Color(0xFFC1D6B7),
    bgGradientMid:               Color(0xFFB5CDAB),
    bgGradientBottom:            Color(0xFF9ABE8E),
    bgGradientTopOpacity:        0.36,
    bgGradientMidOpacity:        0.45,
    bgGradientBottomOpacity:     0.54,
    cardBackground:              Color(0xFFFFFFFF),
    cardBackgroundOpacity:       0.25,
    cardPinned:                  Color(0xFFFFFFFF),
    cardPinnedOpacity:           0.35,
    cardDone:                    Color(0xFFFFFFFF),
    cardDoneOpacity:             0.15,
    cardBrowse:                  Color(0xFFFFFFFF),
    cardBrowseOpacity:           0.30,
    ctaPrimary:                  Color(0xFF5A8A5C),
    ctaSecondary:                Color(0xFF4A7A4C),
    accentPinned:                Color(0xFF5A8A5C),
    accentRegular:               Color(0xFF8AB88A),
    accentCustom:                Color(0xFF7AAA7A),
    accentMuted:                 Color(0xFF7A9A78),
    textPrimary:                 Color(0xFF2C3328),
    textSecondary:               Color(0xFF5A6854),
    textLabel:                   Color(0xFF5A7A5C),
    textSubtitle:                Color(0xFF3E4E3A),
    textTertiary:                Color(0xFF7A8A72),
    textDisabled:                Color(0xFFB0C0A8),
    textMutedBrown:              Color(0xFF5A6854),
    borderCard:                  Color(0xFFFFFFFF),
    borderCardOpacity:           0.52,
    borderMedium:                Color(0xFFC4D4C0),
    borderWarm:                  Color(0xFFD8E4D4),
    divider:                     Color(0xFF5A8A5C),
    dividerOpacity:              0.14,
    checkmarkFill:               Color(0xFF5A8A5C),
    checkmarkBackground:         Color(0xFFA0C8A0),
    checkmarkBackgroundOpacity:  0.40,
    profileCard:                 Color(0xFFFFFFFF),
    profileCardOpacity:          0.50,
    momentsCard:                 Color(0xFFFFFFFF),
    momentsCardOpacity:          0.25,
    modalBg1:                    Color(0xFFE8F0E6),
    modalBg2:                    Color(0xFFE0E8DE),
    modalBg3:                    Color(0xFFD8E0D6),
    modalShadow:                 Color(0xFF2C3328),
    modalInnerShadow:            Color(0xFF8AAA88),
    buttonDark:                  Color(0xFF3E6840),
    buttonText:                  Color(0xFFF2F5F0),
    surfaceLight:                Color(0xFFF0F4EE),
    surfaceLightest:             Color(0xFFF6F8F4),
    tabBarFade:                  Color(0xFF8AA880),
    barrierColor:                Color(0xFF2A3828),
    barrierOpacity:              0.28,
    destructive:                 Color(0xFFC44B3F),
    destructiveDark:             Color(0xFFB5524D),
    error:                       Color(0xFFD84315),
    success:                     Color(0xFF5A8A5C),
    toastText:                   Color(0xFF2C3328),
    onboardingBg1:               Color(0xFFF2F5F0),
    onboardingBg2:               Color(0xFFE4EBE0),
    onboardingBg3:               Color(0xFFD6E2D0),
    onboardingBg4:               Color(0xFFCCD8C6),
    catHealth:        Color(0xFFD96766),
    catMood:          Color(0xFF9B8299),
    catProductivity:  Color(0xFF8B9A6B),
    catHome:          Color(0xFF7B9E8A),
    catRelationships: Color(0xFFC4856E),
    catCreativity:    Color(0xFFB48BA3),
    catFinances:      Color(0xFFC49B5A),
    catSelfCare:      Color(0xFFB8A089),
    backgroundSoft:  'assets/images/background_soft_forestfloor.png',
    backgroundMs:    'assets/images/background_ms_forestfloor.png',
    ctaAlternative:  Color(0xFF5A8A5C),
    completionHeart: Color(0xFF8AB88A),
    heartHighlight:  Color(0xFFA8D0A8),
    heartDeep:       Color(0xFF6A9A6A),
    pinnedAccent:    Color(0xFF4A7A4C),
  );

  // ── Golden Hour ───────────────────────────────────────────────────
  static const AppColorScheme goldenHour = AppColorScheme(
    bgGradientTop:               Color(0xFFD7AA8C),
    bgGradientMid:               Color(0xFFD0A284),
    bgGradientBottom:            Color(0xFFC88E68),
    bgGradientTopOpacity:        0.82,
    bgGradientMidOpacity:        0.86,
    bgGradientBottomOpacity:     0.90,
    cardBackground:              Color(0xFFFFE6D2),
    cardBackgroundOpacity:       0.28,
    cardPinned:                  Color(0xFFFFF2E8),
    cardPinnedOpacity:           0.38,
    cardDone:                    Color(0xFFFFFFFF),
    cardDoneOpacity:             0.22,
    cardBrowse:                  Color(0xFFFFFFFF),
    cardBrowseOpacity:           0.40,
    ctaPrimary:                  Color(0xFFC07A42),
    ctaSecondary:                Color(0xFFAA6A35),
    accentPinned:                Color(0xFFC07A42),
    accentRegular:               Color(0xFFD8A878),
    accentCustom:                Color(0xFFD09060),
    accentMuted:                 Color(0xFFA88068),
    textPrimary:                 Color(0xFF3E2A1A),
    textSecondary:               Color(0xFF8A6548),
    textLabel:                   Color(0xFF8A6548),
    textSubtitle:                Color(0xFF604830),
    textTertiary:                Color(0xFFA88068),
    textDisabled:                Color(0xFFD0B8A0),
    textMutedBrown:              Color(0xFF8A6548),
    borderCard:                  Color(0xFFFFE1C8),
    borderCardOpacity:           0.55,
    borderMedium:                Color(0xFFDCC4A8),
    borderWarm:                  Color(0xFFEAD4BC),
    divider:                     Color(0xFFC07A42),
    dividerOpacity:              0.20,
    checkmarkFill:               Color(0xFFC07A42),
    checkmarkBackground:         Color(0xFFD8B890),
    checkmarkBackgroundOpacity:  0.40,
    profileCard:                 Color(0xFFFFFFFF),
    profileCardOpacity:          0.50,
    momentsCard:                 Color(0xFFFFFFFF),
    momentsCardOpacity:          0.25,
    modalBg1:                    Color(0xFFF5E4D4),
    modalBg2:                    Color(0xFFF0DCCC),
    modalBg3:                    Color(0xFFECD4C4),
    modalShadow:                 Color(0xFF3E2A1C),
    modalInnerShadow:            Color(0xFFB89878),
    buttonDark:                  Color(0xFF8A5A30),
    buttonText:                  Color(0xFFFFF2E8),
    surfaceLight:                Color(0xFFF8F0E8),
    surfaceLightest:             Color(0xFFFCF6F0),
    tabBarFade:                  Color(0xFFA88065),
    barrierColor:                Color(0xFF503820),
    barrierOpacity:              0.28,
    destructive:                 Color(0xFFC44B3F),
    destructiveDark:             Color(0xFFB5524D),
    error:                       Color(0xFFD84315),
    success:                     Color(0xFF6A8B6F),
    toastText:                   Color(0xFF3E2A1A),
    onboardingBg1:               Color(0xFFF2DFD0),
    onboardingBg2:               Color(0xFFE8D0C0),
    onboardingBg3:               Color(0xFFDEC0B0),
    onboardingBg4:               Color(0xFFD4B4A2),
    catHealth:        Color(0xFFD96766),
    catMood:          Color(0xFF9B8299),
    catProductivity:  Color(0xFF8B9A6B),
    catHome:          Color(0xFF7B9E8A),
    catRelationships: Color(0xFFC4856E),
    catCreativity:    Color(0xFFB48BA3),
    catFinances:      Color(0xFFC49B5A),
    catSelfCare:      Color(0xFFB8A089),
    backgroundSoft:  'assets/images/background_soft_goldenhour.png',
    backgroundMs:    'assets/images/background_ms_goldenhour.png',
    ctaAlternative:  Color(0xFFC07A42),
    completionHeart: Color(0xFFD09060),
    heartHighlight:  Color(0xFFE0B088),
    heartDeep:       Color(0xFFB07040),
    pinnedAccent:    Color(0xFFC07A42),
  );

  // ── Night Bloom ───────────────────────────────────────────────────
  static const AppColorScheme nightBloom = AppColorScheme(
    bgGradientTop:               Color(0xFF1A1C34),
    bgGradientMid:               Color(0xFF1E213C),
    bgGradientBottom:            Color(0xFF222644),
    bgGradientTopOpacity:        0.45,
    bgGradientMidOpacity:        0.55,
    bgGradientBottomOpacity:     0.65,
    cardBackground:              Color(0xFF3A3E69),
    cardBackgroundOpacity:       0.88,
    cardPinned:                  Color(0xFF424672),
    cardPinnedOpacity:           0.88,
    cardDone:                    Color(0xFF2A2E50),
    cardDoneOpacity:             0.70,
    cardBrowse:                  Color(0xFF323660),
    cardBrowseOpacity:           0.78,
    ctaPrimary:                  Color(0xFFB0A2D8),
    ctaSecondary:                Color(0xFF9A8CC8),
    accentPinned:                Color(0xFFB0A2D8),
    accentRegular:               Color(0xFF7470A8),
    accentCustom:                Color(0xFF8A86B8),
    accentMuted:                 Color(0xFF6864A0),
    textPrimary:                 Color(0xFFE0DCF0),
    textSecondary:               Color(0xFFB0ACC8),
    textLabel:                   Color(0xFF9490B0),
    textSubtitle:                Color(0xFFC8C4E0),
    textTertiary:                Color(0xFF8B87A8),
    textDisabled:                Color(0xFF6A6890),
    textMutedBrown:              Color(0xFF9490B0),
    borderCard:                  Color(0xFF6469A0),
    borderCardOpacity:           0.42,
    borderMedium:                Color(0xFF4A4E80),
    borderWarm:                  Color(0xFF5A5E90),
    divider:                     Color(0xFFB0A2D8),
    dividerOpacity:              0.20,
    checkmarkFill:               Color(0xFFB0A2D8),
    checkmarkBackground:         Color(0xFF5A5890),
    checkmarkBackgroundOpacity:  0.60,
    profileCard:                 Color(0xFF3A3E69),
    profileCardOpacity:          0.88,
    momentsCard:                 Color(0xFF30345C),
    momentsCardOpacity:          0.80,
    modalBg1:                    Color(0xFF262A4E),
    modalBg2:                    Color(0xFF2C3058),
    modalBg3:                    Color(0xFF323662),
    modalShadow:                 Color(0xFF000000),
    modalInnerShadow:            Color(0xFF4A4E80),
    buttonDark:                  Color(0xFFB0A2D8),
    buttonText:                  Color(0xFF1A1C34),
    surfaceLight:                Color(0xFF2E325A),
    surfaceLightest:             Color(0xFF343862),
    tabBarFade:                  Color(0xFF14162A),
    barrierColor:                Color(0xFF000000),
    barrierOpacity:              0.45,
    destructive:                 Color(0xFFE06050),
    destructiveDark:             Color(0xFFD05545),
    error:                       Color(0xFFE85535),
    success:                     Color(0xFF7A9B7A),
    toastText:                   Color(0xFFE0DCF0),
    onboardingBg1:               Color(0xFF1A1C34),
    onboardingBg2:               Color(0xFF20223A),
    onboardingBg3:               Color(0xFF262A42),
    onboardingBg4:               Color(0xFF2C304A),
    catHealth:        Color(0xFFE07A78),
    catMood:          Color(0xFFB098B0),
    catProductivity:  Color(0xFFA0B080),
    catHome:          Color(0xFF90B4A0),
    catRelationships: Color(0xFFD8A088),
    catCreativity:    Color(0xFFC8A0B8),
    catFinances:      Color(0xFFD8B070),
    catSelfCare:      Color(0xFFC8B098),
    backgroundSoft:  'assets/images/background_soft_nightbloom.png',
    backgroundMs:    'assets/images/background_ms_nightbloom.png',
    ctaAlternative:  Color(0xFFB0A2D8),
    completionHeart: Color(0xFFB0A2D8),
    heartHighlight:  Color(0xFFC8B8E8),
    heartDeep:       Color(0xFF9A88C8),
    pinnedAccent:    Color(0xFFB0A2D8),
  );

  // ── Sand Dune ─────────────────────────────────────────────────────
  static const AppColorScheme sandDune = AppColorScheme(
    bgGradientTop:               Color(0xFFD2C8B6),
    bgGradientMid:               Color(0xFFCAC0AE),
    bgGradientBottom:            Color(0xFFC3AE92),
    bgGradientTopOpacity:        0.62,
    bgGradientMidOpacity:        0.67,
    bgGradientBottomOpacity:     0.72,
    cardBackground:              Color(0xFFEBE4DA),
    cardBackgroundOpacity:       0.28,
    cardPinned:                  Color(0xFFF5F0E8),
    cardPinnedOpacity:           0.38,
    cardDone:                    Color(0xFFFFFFFF),
    cardDoneOpacity:             0.22,
    cardBrowse:                  Color(0xFFFFFFFF),
    cardBrowseOpacity:           0.40,
    ctaPrimary:                  Color(0xFF5C4E3E),
    ctaSecondary:                Color(0xFF4A4034),
    accentPinned:                Color(0xFF5C4E3E),
    accentRegular:               Color(0xFF8A7E72),
    accentCustom:                Color(0xFF7A6E60),
    accentMuted:                 Color(0xFF8A8078),
    textPrimary:                 Color(0xFF332E28),
    textSecondary:               Color(0xFF6A6258),
    textLabel:                   Color(0xFF6A6258),
    textSubtitle:                Color(0xFF4E4840),
    textTertiary:                Color(0xFF8A8078),
    textDisabled:                Color(0xFFB8B0A4),
    textMutedBrown:              Color(0xFF6A6258),
    borderCard:                  Color(0xFFF8F4EE),
    borderCardOpacity:           0.60,
    borderMedium:                Color(0xFFCCC4B8),
    borderWarm:                  Color(0xFFDED6CA),
    divider:                     Color(0xFF5C4E3E),
    dividerOpacity:              0.15,
    checkmarkFill:               Color(0xFF5C4E3E),
    checkmarkBackground:         Color(0xFFB8AEA0),
    checkmarkBackgroundOpacity:  0.40,
    profileCard:                 Color(0xFFFFFFFF),
    profileCardOpacity:          0.50,
    momentsCard:                 Color(0xFFFFFFFF),
    momentsCardOpacity:          0.25,
    modalBg1:                    Color(0xFFF0EAE0),
    modalBg2:                    Color(0xFFE8E2D8),
    modalBg3:                    Color(0xFFE0DAD0),
    modalShadow:                 Color(0xFF332E28),
    modalInnerShadow:            Color(0xFFA09888),
    buttonDark:                  Color(0xFF5C4E3E),
    buttonText:                  Color(0xFFF5F0E8),
    surfaceLight:                Color(0xFFF2EDE4),
    surfaceLightest:             Color(0xFFF8F4EE),
    tabBarFade:                  Color(0xFFA49A88),
    barrierColor:                Color(0xFF3A3428),
    barrierOpacity:              0.28,
    destructive:                 Color(0xFFC44B3F),
    destructiveDark:             Color(0xFFB5524D),
    error:                       Color(0xFFD84315),
    success:                     Color(0xFF6A8B6F),
    toastText:                   Color(0xFF332E28),
    onboardingBg1:               Color(0xFFF0EBE2),
    onboardingBg2:               Color(0xFFE4DED4),
    onboardingBg3:               Color(0xFFD8D2C6),
    onboardingBg4:               Color(0xFFD0C8BC),
    catHealth:        Color(0xFFD96766),
    catMood:          Color(0xFF9B8299),
    catProductivity:  Color(0xFF8B9A6B),
    catHome:          Color(0xFF7B9E8A),
    catRelationships: Color(0xFFC4856E),
    catCreativity:    Color(0xFFB48BA3),
    catFinances:      Color(0xFFC49B5A),
    catSelfCare:      Color(0xFFB8A089),
    backgroundSoft:  'assets/images/background_soft_sanddune.png',
    backgroundMs:    'assets/images/background_ms_sanddune.png',
    ctaAlternative:  Color(0xFF6A8B6F),
    completionHeart: Color(0xFF8A7E72),
    heartHighlight:  Color(0xFFA89888),
    heartDeep:       Color(0xFF6A6058),
    pinnedAccent:    Color(0xFF5C4E3E),
  );

  static AppColorScheme of(AppTheme theme) {
    switch (theme) {
      case AppTheme.warmClay:     return warmClay;
      case AppTheme.iris:         return iris;
      case AppTheme.clearSky:     return clearSky;
      case AppTheme.morningSlate: return morningSlate;
      case AppTheme.softDusk:     return softDusk;
      case AppTheme.deepFocus:    return deepFocus;
      case AppTheme.forestFloor:  return forestFloor;
      case AppTheme.goldenHour:   return goldenHour;
      case AppTheme.nightBloom:   return nightBloom;
      case AppTheme.sandDune:     return sandDune;
    }
  }
}
