// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB45XhesWbQFOFJQ5OeI4olLz1E_x1Rm-c',
    appId: '1:651637918599:android:0a1aa7b2ac3e5a42222122',
    messagingSenderId: '651637918599',
    projectId: 'intended-e613f',
    storageBucket: 'intended-e613f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf5yJ8yjLfzB_D_fH39jrj9LojoHzIaUU',
    appId: '1:651637918599:ios:210a4eb10ae173ca222122',
    messagingSenderId: '651637918599',
    projectId: 'intended-e613f',
    storageBucket: 'intended-e613f.firebasestorage.app',
    iosClientId: '651637918599-pr6s42v9goh36flr17bjbeabrti743fg.apps.googleusercontent.com',
    iosBundleId: 'com.intendedapp.ios',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ZxeDbqvRzbwtTLa7aQRR94ffXl-CyPE',
    appId: '1:651637918599:web:270c79c94ad50003222122',
    messagingSenderId: '651637918599',
    projectId: 'intended-e613f',
    authDomain: 'intended-e613f.firebaseapp.com',
    storageBucket: 'intended-e613f.firebasestorage.app',
    measurementId: 'G-TFGVN9RW88',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf5yJ8yjLfzB_D_fH39jrj9LojoHzIaUU',
    appId: '1:651637918599:ios:d5632a97e0582a72222122',
    messagingSenderId: '651637918599',
    projectId: 'intended-e613f',
    storageBucket: 'intended-e613f.firebasestorage.app',
    iosClientId: '651637918599-69bmvm8rmlc84qiegms6u16ons0oe0ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.gently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ZxeDbqvRzbwtTLa7aQRR94ffXl-CyPE',
    appId: '1:651637918599:web:fa65cfd3f0be15cb222122',
    messagingSenderId: '651637918599',
    projectId: 'intended-e613f',
    authDomain: 'intended-e613f.firebaseapp.com',
    storageBucket: 'intended-e613f.firebasestorage.app',
    measurementId: 'G-QEVVH1X8E6',
  );

}